apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ing-base
  annotations:
    alb.ingress.kubernetes.io/listen-ports: application-base
    alb.ingress.kubernetes.io/load-balancer-size: application-base
    alb.ingress.kubernetes.io/network-type: application-base
    alb.ingress.kubernetes.io/ssl-certificate-no: application-base
    alb.ingress.kubernetes.io/ssl-redirect: application-base
    alb.ingress.kubernetes.io/healthcheck-path: application-base
spec:
  ingressClassName: alb
