apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: application-seonhee
commonLabels:
  name: application-seonhee
images:
- name: :init
  newName: sh-registry.ncr.gov-ntruss.com/application
  newTag: '240802132835'
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: application-seonhee-svc
  target:
    kind: Service
    name: application-base
- patch: |-
    - op: replace
      path: /metadata/name
      value: application-seonhee-deploy
  target:
    kind: Deployment
    name: application-base
- patch: |-
    - op: replace
      path: /metadata/name
      value: application-seonhee-ing
  target:
    kind: Ingress
    name: application-base
